spring.application.name=discografia

# Configuracion conexion a cluster
spring.data.mongodb.uri=mongodb+srv://cristopherfelipe91_db_user:kuzn38r0S83f1Z6F@cluster0.lofoupg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=discografica-db
